version: '3.5'

services:
  api:
    image: e-staff_api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run build && npm run start:prod"

  seed:
    image: e-staff_api
    command: sh -c "sleep 20 && npm run seed"
    volumes:
      - .:/usr/src/app
    links:
      - postgres:postgres
    networks:
      - postgres
    depends_on:
      - postgres
      - api

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_USER=heroes_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=estaff

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
