const EMPLOYEE_REPOSITORY = 'EMPLOYEE_REPOSITORY';
const OFFICE_REPOSITORY = 'OFFICE_REPOSITORY';
const TAG_REPOSITORY = 'TAG_REPOSITORY';
const DATABASE_CONNECTION = 'DATABASE_CONNECTION';

export {
  EMPLOYEE_REPOSITORY,
  DATABASE_CONNECTION,
  OFFICE_REPOSITORY,
  TAG_REPOSITORY,
};
